# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wave' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wave

  pod 'lottie-ios'

  target 'waveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'waveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
